services:
  - type: web
    name: intrepipay
    env: node
    buildCommand: npm install && PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install chromium
    startCommand: node server.js
    plan: free
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
